//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatToday2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int RatingValue { get; set; }
        public System.DateTime RatingDate { get; set; }
        public int Rater_ID { get; set; }
        public int Rest_ID { get; set; }
    
        public virtual Rater Rater { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
